### PR TITLE
Graphql schellar

### PR DESCRIPTION
**Pull request by Jozefiel**

### CODE REVIEW

**Review by marosmars — APPROVED** [review]
LGTM

do we need to change Dockerfile or workflows to invoke go generate graphql during build ?

**Comment by Jozefiel** [comment]
No. Files are generated during the development.
The developer needs to create Graphql schema and use 99designs/gqlgen tool.
That tool creates schema.resolvers.go file, where the developer writes a response. 

command:
`go run github.com/99designs/gqlgen generate
`

**Comment by marosmars** [comment]
> No. Files are generated during the development. The developer needs to create Graphql schema and use 99designs/gqlgen tool. That tool creates schema.resolvers.go file, where the developer writes a response.
> 
> command: `go run github.com/99designs/gqlgen generate `

Yeah that command is what I meant, it generates some files based on schema. So I was wondering whether we should run it with before build just like we do in resource manger.

**Comment by Jozefiel** [comment]
The check was added to GitHub actions.

**Review by MarcoMruz — APPROVED** [review]

**Pull request merged**
